### ISSUE TITLE
filter is case sensitive

### ISSUE THREAD

**Issue by axkibe** [ldapjs/filter#3]
Following minimal testcase:
```
const ldap = require( 'ldapjs' );
const attr = {};
attr.cn = 'axel';
attr.gidNumber = '1001';
attr.uidNumber = '1001'
attr.uid = 'axel';
attr.displayName = 'axel';
attr.loginShell = '/bin/bash';
attr.homeDirectory = '/home/axel';
attr.objectclass = [ 'posixAccount', 'top' ];
const f = ldap.parseFilter('(objectClass=*)');
console.log( f.matches( attr ) );
```
The result with node-ldapjs 2.3.3 is true, in node-ldapjs 3.0.1 it is false.

Note the uppercase C, writing it lowercase gives the IMO correct true (or changing the attribute to match the same case)

AFAIK LDAP is supposed to be case insensitive on attributes by default, as 2.3.3 did, no?

**Comment by jsumners** [comment]
LDAP filter strings are defined by https://www.rfc-editor.org/rfc/rfc4515

LDAP attributes (`<attributedescription> = <attributevalue>`) are defined by https://www.rfc-editor.org/rfc/rfc4512#section-2.5 and https://www.rfc-editor.org/rfc/rfc4512#section-2.5.1. Specific to this issue:

> Both `<attributetype>` and `<option>`
   productions are case insensitive.  The order in which <option>s
   appear is irrelevant.  That is, any two `<attributedescription>s` that
   consist of the same `<attributetype>` and same set of `<option>s` are
   equivalent.

So it can be correct to say that `objectclass === objectClass` when comparing two attributes.

Scattered throughout the `ldapjs <= 2` code were blocks that looked like:

```js
if (prop.toLowerCase() === 'objectclass') {
  // do some check or something
}
```

Such blocks would have a comment attached like:

```js
// Comparing case insensitive since most implementations do that for objectClass
```

To be clear: the `ldapjs <= 2` code made an _explicit exception_ for `objectClass`. For all other attribute types it defaulted to case sensitive comparisons.

In general, the spec is muddy on what to do in regard to attribute type comparisons. The closest we get is the discussion around the compare operation and the ensuing descriptions of various filters -- https://www.rfc-editor.org/rfc/rfc4511#section-4.10.

However, we retained the original case insensitive comparison feature:

```js
const ldap = require( 'ldapjs' );
const attr = {};
attr.cn = 'axel';
attr.gidNumber = '1001';
attr.uidNumber = '1001'
attr.uid = 'axel';
attr.displayName = 'axel';
attr.loginShell = '/bin/bash';
attr.homeDirectory = '/home/axel';
attr.objectclass = [ 'posixAccount', 'top' ];
const f = ldap.parseFilter('(objectClass=*)');
console.log(
  f.matches( attr, false )
);
```

Note the inclusion of a second parameter being passed to `f.matches`. See the following declaration in the `AND` filter as an example:

https://github.com/ldapjs/filter/blob/e70a7cba6c17310956e87a9b28e6bea61db48d93/lib/filters/and.js#L54-L73

**Comment by axkibe** [comment]
Thanks for your detailed explanation.

I searched if I rather should set "objectclass" or "objectClass" and it seems the internet is all over the place. Basically as workaround other than ,false as second parameter I can also set both attributes.

**Comment by jsumners** [comment]
I have updated the [v3 release notes](https://github.com/ldapjs/node-ldapjs/releases/tag/v3.0.0) with this information.
